title: WebCrate Testing Site
baseurl: /
permalink: '/:title/'
layout_style: overflow
palette: orange
header:
  bg: dark
  has_nav: true
  has_social: true
  profile_img: /images/webcratev2.png
  tagline: WebCrate Makes Documentation Easy
  title: WebCrate
footer:
  content: '&copy; All rights reserved @WebCrate'
  links:
    - new_window: true
      text: 'Purchase a Site Through WebCrate '
      url: 'https://discord.gg/sW4Xt2x'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
